spring.application.name=githubreview
server.port=8080

# ==========================================
# GitHub & Webhook Security
# ==========================================
github.webhook.secret=${GITHUB_WEBHOOK_SECRET}
github.api.token=${GITHUB_PAT}

# ==========================================
# Groq AI Configuration
# ==========================================
groq.api.url=https://api.groq.com/openai/v1
groq.api.key=${GROQ_API_KEY}
groq.model.name=llama-3.3-70b-versatile

# ==========================================
# PostgreSQL Cloud Database (Neon.tech)
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-floral-tree-aqpdxwp6.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# OAuth Configurations
# ==========================================
# Google OAuth
spring.security.oauth2.client.registration.google.client-id=1054242920494-3gv1od0aslnbf7sqkuumpr3ptu1kesrv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# GitHub OAuth
spring.security.oauth2.client.registration.github.client-id=Ov23liEYoqLTaHVuotn0
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Server Settings
server.forward-headers-strategy=native